let items = [{
    id: 1,
    image: "/assets/image/English.jpg",
    name: "English",
    location: "Dartford",
    price: 16.50,
    space: 5,
},

{
    id: 2,
    image: "/assets/image/Maths.jpg",
    name: "Math",
    location: "Oxford",
    price: 23.50,
    space: 5,
},
{
    id: 3,
    image: "/assets/image/Science.png",
    name: "Science",
    location: "bexleyheath",
    price: 40.50,
    space: 5,
},
{
    id: 4,
    image: "/assets/image/Music.png",
    name: "Music",
    location: "bexleyheath",
    price: 32.50,
    space: 5,
},
{
    id: 5,
    image: "/assets/image/Art.jpg",
    name: "Art",
    location: "Oxford",
    price: 60.50,
    space: 5,
},
{
    id: 6,
    image: "/assets/image/Higher Maths.png",
    name: "Higher Maths",
    location: "Oxford",
    price: 25.43,
    space: 5,
},
{
    id: 7,
    image: "/assets/image/History.jpg",
    name: "History",
    location: "Dartford",
    price: 25.30,
    space: 5,
},
{
    id: 8,
    image: "/assets/image/R.E.jpg",
    name: "R.E",
    location: "Erith",
    price: 45.50,
    space: 5,
},
{
    id: 9,
    image: "/assets/image/Physics.jpg",
    name: "Physics",
    location: "Erith",
    price: 32.00,
    space: 5,
},
{
    id: 10,
    image: "/assets/mage/Computer Science.jpg",
    name: "Computer Science",
    location: "Erith",
    price: 27.50,
    space: 5,
},
]